cat-fact:
    url: https://catfact.ninja/facts
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
        url: jdbc:mysql://mysql:3306/bookstore?noSSL=trueuse&LegacyDatetimeCode=false&serverTimezone=UTC
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
                id:
                    new_generator_mappings: false
